Create Email Verification Page
andr-dev/CS446 pull request #18
Opened 2023-06-06 15:42 UTC by Jiay0928

<img width="363" alt="Screen Shot 24" src="https://github.com/andr-dev/CS446/assets/56942420/1b36f777-7c5c-4918-83a3-a8da915e264b">

2023-06-06 16:05 UTC, leeminkyu16 reviewed
Overall pretty good, just some small changes here and there are needed ^-^

2023-06-06 16:05 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageView.kt
> +    {Column(
Weird spacing

2023-06-06 16:05 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageView.kt
> +
I don't think you need the extra lines here?

2023-06-06 16:05 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageView.kt
> +            modifier = modifier.fillMaxWidth(0.77f) ,
Use `Modifier` not `modifier` here.
The styling that is passed should not affect the textfield.
 
Also, space after modifier.fillMaxWidth for no reason?

2023-06-06 16:05 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageView.kt
> +    onNavigateToHome: () -> Unit,
I think we can just pass in the `navHostController` instead.

It is fine to have the function here, but in cases where there are a bunch of screen that you can navigate to on a page, it's cleaner to just have the `navHostController` I think?

2023-06-06 16:05 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageView.kt
> +fun TextFieldBox(index:Int, focusManager:FocusManager,viewModel: EmailVerificationPageViewModel,uiState: EmailVerificationPageUiState = viewModel.uiStateStream.subscribeAsState(
Can you put this on multiple lines and not one?

Also, you can probably make a separate file for this these composables?

Also, is there a reason why we need to pass in the whole `viewModel` here?

2023-06-06 16:05 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageView.kt
> +                textAlign = TextAlign.Justify
Add trailing comma ^-^

2023-06-06 16:05 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageView.kt
> +
Weird extra spaces here

2023-06-06 16:05 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageView.kt
> +
Extra spaces

2023-06-06 16:05 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageViewModel.kt
> +			verificationCode = immutableListOf("","","","","")
I think you can just use `listOf` here

2023-06-06 16:05 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageUiState.kt
> +}
New line at end of new file?

Can you make sure that your code more or less passes Detekt? (Ignore the "function too long" one because that's stupid)

2023-06-06 16:05 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageView.kt
> +    var sublrPink = subletrPink
These should be `val`s?
I don't think they'll change

2023-06-06 16:05 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageView.kt
> +fun VerificationCodeTextField( viewModel: EmailVerificationPageViewModel) {
You shouldn't need to pass in the `viewModel` here?
Just a `value` and `onChange` I would imagine?

2023-06-06 16:05 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageView.kt
> +    var text by remember { mutableStateOf(TextFieldValue("")) }
Should probably rely on the `uiState` instead.

2023-06-06 16:05 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageView.kt
> +               val newCode = uiState.verificationCode.toMutableList()
Instead of making a new mutable list and all that, you can just map the change into the list with `.map` or in this case, probably `.indexedMap`.

2023-06-06 16:48 UTC, andr-dev commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageView.kt
> +            modifier = modifier.fillMaxWidth(0.77f) ,
Hmm what's 0.77f for?

2023-06-06 16:48 UTC, andr-dev commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageView.kt
> +            modifier = Modifier.weight(weight = 13.0f)
13.0f?

2023-06-06 16:48 UTC, andr-dev commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageView.kt
> +            .height(56.dp)
Please use 56 for both, if not it's barely not a square.

2023-06-06 16:49 UTC, andr-dev requested changes
Noticed there's a merge in your commit history, please rebase to keep it linear.

2023-06-06 16:56 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageView.kt
> +            modifier = modifier.fillMaxWidth(0.77f) ,
Probably for the width of the elements on screen.
Should be a `const` though....

2023-06-06 19:13 UTC, Jiay0928 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageView.kt
> +            modifier = modifier.fillMaxWidth(0.77f) ,
Would it be better if I store all width/height as const?

2023-06-06 19:15 UTC, Jiay0928 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageView.kt
> +            modifier = Modifier.weight(weight = 13.0f)
It's the space between components, like a weighted portion of the remaining space.

2023-06-07 14:13 UTC, leeminkyu16 approved these changes
Just one small thing.
Also, if you could change your `dp` spacing to the new standard that we added (if you want, I can do it if you want).

Otherwise, Let's Gamble Try Merging (even though we rebase on master lol)

2023-06-07 14:13 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/emailverification/EmailVerificationPageView.kt
> +		textStyle = TextStyle(
Sorry, can you make a constant in Typography for this (so that we can standardize these things)?

2023-06-07 16:29 UTC, andr-dev approved these changes

2023-06-09 00:24 UTC, leeminkyu16 commented
Just a quick thing, I think changing `labelMedium` is changing the way the bottom bar looks.
Can you just make sure that it still looks okay?

2023-06-09 01:53 UTC, Jiay0928 commented
> Just a quick thing, I think changing `labelMedium` is changing the way the bottom bar looks. Can you just make sure that it still looks okay?

The bottom bar is not using any Typography format. It is fine.

2023-06-09 01:55 UTC, andr-dev approved these changes
Nice! Happy with this, let's merge!

2023-06-09 01:56 UTC, merged