Create Location and Price Filter
andr-dev/CS446 pull request #84
Opened 2023-07-03 18:32 UTC by Jiay0928

<img width="251" alt="Screen Shot 15" src="https://github.com/andr-dev/CS446/assets/56942420/00f850e3-549f-4691-a304-086069c6099d">
<img width="254" alt="Screen Shot 16" src="https://github.com/andr-dev/CS446/assets/56942420/c63ccd1d-f489-4d56-bf9e-3a45118b5dab">

2023-07-03 19:07 UTC, leeminkyu16 reviewed
Just a few comments

2023-07-03 19:07 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/home/list/HomeListChildView.kt
> +			sheetContainerColor = Color.White,
Can you make this a dark-mode-conscious colour?

2023-07-03 19:07 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/home/list/HomeListChildView.kt
> +			modifier = Modifier.fillMaxSize(1.0f),
Should be `modifier`, I think.

2023-07-03 19:07 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/home/list/HomeListChildView.kt
> +					modifier = modifier
Should be `Modifier`, I think.

2023-07-03 19:07 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/home/list/components/filters.kt
> +fun LocationFilterForm(
Can you make the separate components into separate files?

2023-07-03 19:07 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/home/list/HomeListChildViewModel.kt
> +							priceMax = priceRangeFilterStream.value!!.upperBound,
Use `getListingParams` here.
`Observable.value` should basically never be used.

2023-07-03 19:07 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/home/list/HomeListChildView.kt
> +						),
I don't think you should need this?

2023-07-03 19:07 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/home/list/HomeListChildView.kt
> +									iconId = R.drawable.tune_round_black_24,
I know you didn't really change this in this PR but can you add a TODO to make this dark mode conscious?

2023-07-03 19:07 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/home/list/components/filters.kt
> +					modifier = Modifier/**/.clickable {
Random comment?

2023-07-03 19:07 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/home/list/components/filters.kt
> +						.fillMaxWidth()
Add trailing comma

2023-07-03 19:07 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/home/list/components/filters.kt
> +							dimensionResource(id = R.dimen.xxs)
Add trailing comma.
Also, can you make these named parameters (makes the code easier to read).

2023-07-03 19:07 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/home/list/components/filters.kt
> +					horizontalArrangement = Arrangement.SpaceBetween
Add trailing comma

2023-07-03 19:07 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/home/list/components/filters.kt
> +							style = filterBoldFont
Add trailing comma

2023-07-03 19:07 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/home/list/components/filters.kt
> +			verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.s))
Add trailing comma

2023-07-03 19:07 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/home/list/components/filters.kt
> +		suffix = suffix
Add trailing comma

2023-07-03 19:07 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/home/list/HomeListChildView.kt
> +									}
Add trailing comma

2023-07-03 19:07 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/home/list/HomeListChildView.kt
> +										}
Add trailing comma

2023-07-03 19:27 UTC, AhbedShawarma requested changes
Couple things that may or may not be easy to fix:
1. When a filter is clicked and a bottom sheet appears, the screen behind should not be clickable. This creates weird behaviour where the user can't click above the filter's bottom sheet to close it which is pretty standard. The bottom sheet that you need is `ModalBottomSheet`, I used this for my datepicker bottom sheet as well.
2. Idk how solvable this is but when you open the keyboard in the filter screen, it adds a lot of white space between the keyboard and the contents of the bottom sheet. Also if you close the bottom sheet while the keyboard is open, that white spacing stays there above the keyboard and it looks really weird.

2023-07-03 19:27 UTC, AhbedShawarma commented on android/app/src/main/res/values/strings.xml
> +    <string name="km">Km</string>
small thing, but this should be lowercase "km"

2023-07-03 23:53 UTC, AhbedShawarma approved these changes
changes look great, nice work!

2023-07-04 00:38 UTC, leeminkyu16 approved these changes
Can you just split the `filters.kt` into the separate forms (will help it when we add all the filters)?
Otherwise, Let's Gamble, Try Merging.

2023-07-04 00:38 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/home/list/HomeListChildView.kt
> +										) { closeBottomSheet() }
Just a small thing but you can do `::closeBottomSheet` instead of creating another lambda function

2023-07-04 00:38 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/home/list/HomeListChildView.kt
> +									) { closeBottomSheet() }
Just a small thing but you can do `::closeBottomSheet` instead of creating another lambda function

2023-07-04 00:38 UTC, leeminkyu16 commented on android/app/src/main/java/org/uwaterloo/subletr/pages/home/list/components/filters.kt
> +					modifier = Modifier/**/.clickable {
Still random `/**/`

2023-07-05 14:06 UTC, leeminkyu16 approved these changes
Let's Gamble, Try Merging

2023-07-05 14:07 UTC, merged